In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:95% !important; }</style>"))

# Practica 3 (10%) - Práctica de manejo de módulos y funciones

In [27]:
import pandas as pd
import numpy as np
import os
import plotly.graph_objects as go
from ipywidgets import widgets, interactive, interactive_output, interact
from datetime import datetime, timedelta

## 1. Creación de variables, funciones y objetos

#### Carga de archivos.

In [106]:
data = pd.read_excel('data/owid-covid-data.xlsx')
data

,iso_code,continent,location,date,total_cases,new_cases,total_deaths,new_deaths,total_cases_per_million,new_cases_per_million,...,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cvd_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand
0,AFG,Asia,Afghanistan,2019-12-31,0,0,0,0,0.0,0.0,...,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5
1,AFG,Asia,Afghanistan,2020-01-01,0,0,0,0,0.0,0.0,...,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5
2,AFG,Asia,Afghanistan,2020-01-02,0,0,0,0,0.0,0.0,...,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5
3,AFG,Asia,Afghanistan,2020-01-03,0,0,0,0,0.0,0.0,...,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5
4,AFG,Asia,Afghanistan,2020-01-04,0,0,0,0,0.0,0.0,...,2.581,1.337,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22657,NaN,NaN,International,2020-02-28,705,0,4,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22658,NaN,NaN,International,2020-02-29,705,0,6,2,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22659,NaN,NaN,International,2020-03-01,705,0,6,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22660,NaN,NaN,International,2020-03-02,705,0,6,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22661,NaN,NaN,International,2020-03-10,696,-9,7,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [108]:
data_country_iso_code = pd.read_excel('data/coutry_iso_code.xlsx')
data_country_iso = pd.DataFrame(columns=['Nombre del país'], index = data_country_iso_code['ISO 3166-1 .1'])
data_country_iso['Nombre del país'] = list(data_country_iso_code['Nombre del país'])
data_country_iso

                      Nombre del país
ISO 3166-1 .1
AND                           Andorra
ARE            Emiratos Árabes Unidos
AFG                        Afganistán
ATG                 Antigua y Barbuda
AIA                           Anguila
...                               ...
WLF                   Wallis y Futuna
WSM                             Samoa
YEM                             Yemen
MYT                           Mayotte
ZAF                         Sudáfrica

[240 rows x 1 columns]

#### Subprograma graficación.

In [2]:
def new_graphic(x1,y1,y2,y1_title,y2_title,y_title):

    fig= go.FigureWidget()
    fig.add_trace(go.Scatter( x=x1, y=y1,
                        mode='lines',
                        name=y1_title))
    fig.add_trace(go.Scatter(x=x1, y=y2,
                        mode='lines',
                        name=y2_title ))
    fig = fig.update_layout(template= 'plotly_dark',title= y1_title +'    '+ y2_title,
                       xaxis_title='Días',
                       yaxis_title=y_title)
    
    return(fig)

#### Creamos lista de fechas.

In [78]:
fecha_inicio = datetime(2020,1,1)
fecha_fin= datetime(2020,8,6)

list_date = [(fecha_inicio + timedelta(days=d)).strftime("%Y-%m-%d")
                    for d in range((fecha_fin - fecha_inicio).days + 1)] 
len(list_date)

219

#### Subprograma de generador de DataFrames de pais.

In [98]:
def gen_coutry_data (iso_code):
    list_total_cases = []
    list_new_cases = []
    list_total_deaths = []
    list_new_deaths = []
    for j in range (len(data)):
        if data['iso_code'][j]== iso_code:
            list_total_cases.append(data['total_cases'][j])
            list_new_cases.append(data['new_cases'][j])
            list_total_deaths.append(data['total_deaths'][j]) 
            list_new_deaths.append(data['new_deaths'][j]) 
            
    n = len(list_date)-len(list_new_cases)
    df_country_name= pd.DataFrame(columns=('date', 'total_cases', 'new_cases','total_deaths', 'new_deaths'))
    df_country_name['date'] = np.zeros(len(list_date))
    df_country_name['total_cases'] =np.zeros(len(list_date))
    df_country_name['new_cases'] = np.zeros(len(list_date))
    df_country_name['total_deaths'] = np.zeros(len(list_date))
    df_country_name['new_deaths'] =np.zeros(len(list_date))
    
    for g in range (len(list_new_cases)):
            df_country_name['total_cases'][g+n] = list_total_cases[g]
            df_country_name['new_cases'][g+n] = list_new_cases[g]
            df_country_name['total_deaths'][g+n]= list_total_deaths[g]
            df_country_name['new_deaths'][g+n]= list_new_deaths[g]
    df_country_name['date'] = list_date.copy()
    return (df_country_name)

#### Creación de gráficos.

In [10]:
x = [0,1,2,3,4,5,6,7,8,9,10]
fig_UpLeft=new_graphic([1,2,3,4,5],[1,4,9,16,25],[1,2,3,4,5],'$$y=x^2$$','$$y=x$$','#s') # Gráfico Up-left
fig_UpRight=new_graphic([1,2,3,4,5,6,7,8,9,10],np.sin(x),np.cos(x),'$$y=sin(x)$$','$$y=cos(x)$$','#s') # Gráfico Up-Right
fig_DownLeft = new_graphic([1,2,3,4,5,6,7,8,9,10],np.exp(x),np.tan(x),'$$y=exp(x)$$','$$y=tan(x)$$','#s') # Gráfico Down-left
fig_DownRight = new_graphic([1,2,3,4,5,6,7,8,9,10],[1+1,2+1,3+1,4+1,5+1,6+1,7+1,8+1,9+1,10+1],[-1,-2,-3,-4,-5,-6,-7,-8,-9,-10],'$$y=x+1$$','$$y=-x-2$$','#s') #Gráfico Down-Right

#### Encabezado

In [4]:
file = open("encabezado.png", "rb")
image = file.read()
img_encabezado= widgets.Image(
    value=image,
    format='png',
    width=1400,
    height=200,
)

#### Tabla

In [5]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

import pandas as pd
import re

df = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/Mining-BTC-180.csv")

for i, row in enumerate(df["Date"]):
    p = re.compile(" 00:00:00")
    datetime = p.split(df["Date"][i])[0]
    df.iloc[i, 1] = datetime

fig_tabla = go.FigureWidget(go.Table(
        header=dict(
            values=["Date", "Number<br>Transactions", "Output<br>Volume (BTC)",
                    "Market<br>Price", "Hash<br>Rate", "Cost per<br>trans-USD",
                    "Mining<br>Revenue-USD", "Trasaction<br>fees-BTC"],
            font=dict(size=10),
            align="left"
        ),
        cells=dict(
            values=[df[k].tolist() for k in df.columns[1:]],
            align = "left")
    ))


fig_table=fig_tabla.update_layout(margin = {'r':0,'b':20,'t':20,'l':0},
            height=1000,         
            width = 400,
            showlegend=False,
            title_text="Bitcoin mining stats for 180 days",
            template= 'plotly_dark'
        )

#### Título

In [6]:
Title=widgets.Textarea(
        value='CORONA VIRUS',
        placeholder='Type something',
        #description='String:',
        disabled=False
    )

#### Selector del país

In [137]:
list_options=[]
for i in range(len(df_summary_covid_ascendent)):
    list_options.append((df_summary_covid_ascendent['Nombre del país'][i] , i+1))

country_selector= widgets.Dropdown(
                options=list_options,
                value=2,
                description='Number:',
                )

#### Selector de tiempo

In [102]:
time_selector = widgets.SelectionRangeSlider(
                options=list_date,
                index=(0, 11),
                description='Months (2015)',
                disabled=False
                )

## 2. Funcionalidad del aplicativo

In [111]:
list_country_iso=data_country_iso_code['ISO 3166-1 .1']
dic_countrys_df={}
for i in range(len(list_country_iso)):
    dic_countrys_df[list_country_iso[i]]=gen_coutry_data (list_country_iso[i])

{'AND':            date  total_cases  new_cases  total_deaths  new_deaths
 0    2020-01-01          0.0        0.0           0.0         0.0
 1    2020-01-02          0.0        0.0           0.0         0.0
 2    2020-01-03          0.0        0.0           0.0         0.0
 3    2020-01-04          0.0        0.0           0.0         0.0
 4    2020-01-05          0.0        0.0           0.0         0.0
 ..          ...          ...        ...           ...         ...
 214  2020-08-02        851.0        7.0          51.0         0.0
 215  2020-08-03        852.0        1.0          51.0         0.0
 216  2020-08-04        852.0        0.0          51.0         0.0
 217  2020-08-05        852.0        0.0          51.0         0.0
 218  2020-08-06        852.0        0.0          51.0         0.0

 [219 rows x 5 columns],
 'ARE':            date  total_cases  new_cases  total_deaths  new_deaths
 0    2020-01-01          0.0        0.0           0.0         0.0
 1    2020-01-02          0.0        0.0           0.0         0.0
 2    2020-01-03          0.0        0.0           0.0         0.0
 3    2020-01-04          0.0        0.0           0.0         0.0
 4    2020-01-05          0.0        0.0           0.0         0.0
 ..          ...          ...        ...           ...         ...
 214  2020-08-02      36359.0      571.0         270.0         1.0
 215  2020-08-03      37018.0      659.0         273.0         3.0
 216  2020-08-04      37642.0      624.0         274.0         1.0
 217  2020-08-05      38268.0      626.0         275.0         1.0
 218  2020-08-06      38808.0      540.0         276.0         1.0

 [219 rows x 5 columns],
 'AFG':            date  total_cases  new_cases  total_deaths  new_deaths
 0    2020-01-01          0.0        0.0           0.0         0.0
 1    2020-01-02          0.0        0.0           0.0         0.0
 2    2020-01-03          0.0        0.0           0.0         0.0
 3    2020-01-04          0.0        0.0           0.0         0.0
 4    2020-01-05          0.0        0.0           0.0         0.0
 ..          ...          ...        ...           ...         ...
 214  2020-08-02      17267.0      758.0         294.0        24.0
 215  2020-08-03      18054.0      787.0         300.0         6.0
 216  2020-08-04      18969.0      915.0         309.0         9.0
 217  2020-08-05      19551.0      582.0         327.0        18.0
 218  2020-08-06      20342.0      791.0         357.0        30.0

 [219 rows x 5 columns],
 'ATG':            date  total_cases  new_cases  total_deaths  new_deaths
 0    2020-01-01          0.0        0.0           0.0         0.0
 1    2020-01-02          0.0        0.0           0.0         0.0
 2    2020-01-03          0.0        0.0           0.0         0.0
 3    2020-01-04          0.0        0.0           0.0         0.0
 4    2020-01-05          0.0        0.0           0.0         0.0
 ..          ...          ...        ...           ...         ...
 214  2020-08-02         26.0        1.0           3.0         0.0
 215  2020-08-03         26.0        0.0           3.0         0.0
 216  2020-08-04         26.0        0.0           3.0         0.0
 217  2020-08-05         26.0        0.0           3.0         0.0
 218  2020-08-06         26.0        0.0           3.0         0.0

 [219 rows x 5 columns],
 'AIA':            date  total_cases  new_cases  total_deaths  new_deaths
 0    2020-01-01          0.0        0.0           0.0         0.0
 1    2020-01-02          0.0        0.0           0.0         0.0
 2    2020-01-03          0.0        0.0           0.0         0.0
 3    2020-01-04          0.0        0.0           0.0         0.0
 4    2020-01-05          0.0        0.0           0.0         0.0
 ..          ...          ...        ...           ...         ...
 214  2020-08-02          3.0        0.0           0.0         0.0
 215  2020-08-03          3.0        0.0           0.0         0.0
 216  2020-08-04          3.0        0.0           0.0         0.0
 217  2020-08-05          3.0        0.0           0.0         0.0
 218  2020-08-06          3.0        0.0           0.0         0.0

 [219 rows x 5 columns],
 'ALB':            date  total_cases  new_cases  total_deaths  new_deaths
 0    2020-01-01          0.0        0.0           0.0         0.0
 1    2020-01-02          0.0        0.0           0.0         0.0
 2    2020-01-03          0.0        0.0           0.0         0.0
 3    2020-01-04          0.0        0.0           0.0         0.0
 4    2020-01-05          0.0        0.0           0.0         0.0
 ..          ...          ...        ...           ...         ...
 214  2020-08-02       1184.0       20.0          33.0         0.0
 215  2020-08-03       1197.0       13.0          33.0         0.0
 216  2020-08-04       1212.0       15.0          33.0         0.0
 217  2020-08-05       1232.0       20.0          34.0         1.0
 218  2020-08-06       1246.0       14.0          34.0         0.0

 [219 rows x 5 columns],
 'ARM':            date  total_cases  new_cases  total_deaths  new_deaths
 0    2020-01-01          0.0        0.0           0.0         0.0
 1    2020-01-02          0.0        0.0           0.0         0.0
 2    2020-01-03          0.0        0.0           0.0         0.0
 3    2020-01-04          0.0        0.0           0.0         0.0
 4    2020-01-05          0.0        0.0           0.0         0.0
 ..          ...          ...        ...           ...         ...
 214  2020-08-02      10524.0      515.0         170.0        12.0
 215  2020-08-03      11221.0      697.0         176.0         6.0
 216  2020-08-04      11817.0      596.0         183.0         7.0
 217  2020-08-05      12364.0      547.0         190.0         7.0
 218  2020-08-06      13130.0      766.0         200.0        10.0

 [219 rows x 5 columns],
 'ANT':            date  total_cases  new_cases  total_deaths  new_deaths
 0    2020-01-01          0.0        0.0           0.0         0.0
 1    2020-01-02          0.0        0.0           0.0         0.0
 2    2020-01-03          0.0        0.0           0.0         0.0
 3    2020-01-04          0.0        0.0           0.0         0.0
 4    2020-01-05          0.0        0.0           0.0         0.0
 ..          ...          ...        ...           ...         ...
 214  2020-08-02          0.0        0.0           0.0         0.0
 215  2020-08-03          0.0        0.0           0.0         0.0
 216  2020-08-04          0.0        0.0           0.0         0.0
 217  2020-08-05          0.0        0.0           0.0         0.0
 218  2020-08-06          0.0        0.0           0.0         0.0

 [219 rows x 5 columns],
 'AGO':            date  total_cases  new_cases  total_deaths  new_deaths
 0    2020-01-01          0.0        0.0           0.0         0.0
 1    2020-01-02          0.0        0.0           0.0         0.0
 2    2020-01-03          0.0        0.0           0.0         0.0
 3    2020-01-04          0.0        0.0           0.0         0.0
 4    2020-01-05          0.0        0.0           0.0         0.0
 ..          ...          ...        ...           ...         ...
 214  2020-08-02         86.0        0.0           4.0         0.0
 215  2020-08-03         86.0        0.0           4.0         0.0
 216  2020-08-04         86.0        0.0           4.0         0.0
 217  2020-08-05         86.0        0.0           4.0         0.0
 218  2020-08-06         91.0        5.0           4.0         0.0

 [219 rows x 5 columns],
 'ATA':            date  total_cases  new_cases  total_deaths  new_deaths
 0    2020-01-01          0.0        0.0           0.0         0.0
 1    2020-01-02          0.0        0.0           0.0         0.0
 2    2020-01-03          0.0        0.0           0.0         0.0
 3    2020-01-04          0.0        0.0           0.0         0.0
 4    2020-01-05          0.0        0.0           0.0         0.0
 ..          ...          ...        ...           ...         ...
 214  2020-08-02          0.0        0.0           0.0         0.0
 215  2020-08-03          0.0        0.0           0.0         0.0
 216  2020-08-04          0.0        0.0           0.0         0.0
 217  2020-08-05          0.0        0.0           0.0         0.0
 218  2020-08-06          0.0        0.0           0.0         0.0

 [219 rows x 5 columns],
 'ARG':            date  total_cases  new_cases  total_deaths  new_deaths
 0    2020-01-01          0.0        0.0           0.0         0.0
 1    2020-01-02          0.0        0.0           0.0         0.0
 2    2020-01-03          0.0        0.0           0.0         0.0
 3    2020-01-04          0.0        0.0           0.0         0.0
 4    2020-01-05          0.0        0.0           0.0         0.0
 ..          ...          ...        ...           ...         ...
 214  2020-08-02      19255.0      949.0         583.0        14.0
 215  2020-08-03      19255.0        0.0         588.0         5.0
 216  2020-08-04      21024.0     1769.0         632.0        44.0
 217  2020-08-05      22007.0      983.0         648.0        16.0
 218  2020-08-06      22781.0      774.0         664.0        16.0

 [219 rows x 5 columns],
 'ASM':            date  total_cases  new_cases  total_deaths  new_deaths
 0    2020-01-01          0.0        0.0           0.0         0.0
 1    2020-01-02          0.0        0.0           0.0         0.0
 2    2020-01-03          0.0        0.0           0.0         0.0
 3    2020-01-04          0.0        0.0           0.0         0.0
 4    2020-01-05          0.0        0.0           0.0         0.0
 ..          ...          ...        ...           ...         ...
 214  2020-08-02          0.0        0.0           0.0         0.0
 215  2020-08-03          0.0        0.0           0.0         0.0
 216  2020-08-04          0.0        0.0           0.0         0.0
 217  2020-08-05          0.0        0.0           0.0         0.0
 218  2020-08-06          0.0        0.0           0.0         0.0

 [219 rows x 5 columns],
 'AUT':            date  total_cases  new_cases  total_deaths  new_deaths
 0    2020-01-01          0.0        0.0           0.0         0.0
 1    2020-01-02          0.0        0.0           0.0         0.0
 2    2020-01-03          0.0        0.0           0.0         0.0
 3    2020-01-04          0.0        0.0           0.0         0.0
 4    2020-01-05          0.0        0.0           0.0         0.0
 ..          ...          ...        ...           ...         ...
 214  2020-08-02      16705.0       31.0         670.0         1.0
 215  2020-08-03      16741.0       36.0         670.0         0.0
 216  2020-08-04      16803.0       62.0         672.0         2.0
 217  2020-08-05      16822.0       19.0         672.0         0.0
 218  2020-08-06      16868.0       46.0         672.0         0.0

 [219 rows x 5 columns],
 'AUS':            date  total_cases  new_cases  total_deaths  new_deaths
 0    2020-01-01          0.0        0.0           0.0         0.0
 1    2020-01-02          0.0        0.0           0.0         0.0
 2    2020-01-03          0.0        0.0           0.0         0.0
 3    2020-01-04          0.0        0.0           0.0         0.0
 4    2020-01-05          0.0        0.0           0.0         0.0
 ..          ...          ...        ...           ...         ...
 214  2020-08-02       7229.0        8.0         102.0         0.0
 215  2020-08-03       7240.0       11.0         102.0         0.0
 216  2020-08-04       7251.0       11.0         102.0         0.0
 217  2020-08-05       7255.0        4.0         102.0         0.0
 218  2020-08-06       7260.0        5.0         102.0         0.0

 [219 rows x 5 columns],
 'ABW':            date  total_cases  new_cases  total_deaths  new_deaths
 0    2020-01-01          0.0        0.0           0.0         0.0
 1    2020-01-02          0.0        0.0           0.0         0.0
 2    2020-01-03          0.0        0.0           0.0         0.0
 3    2020-01-04          0.0        0.0           0.0         0.0
 4    2020-01-05          0.0        0.0           0.0         0.0
 ..          ...          ...        ...           ...         ...
 214  2020-08-02        101.0        0.0           3.0         0.0
 215  2020-08-03        101.0        0.0           3.0         0.0
 216  2020-08-04        101.0        0.0           3.0         0.0
 217  2020-08-05        101.0        0.0           3.0         0.0
 218  2020-08-06        101.0        0.0           3.0         0.0

 [219 rows x 5 columns],
 'ALA':            date  total_cases  new_cases  total_deaths  new_deaths
 0    2020-01-01          0.0        0.0           0.0         0.0
 1    2020-01-02          0.0        0.0           0.0         0.0
 2    2020-01-03          0.0        0.0           0.0         0.0
 3    2020-01-04          0.0        0.0           0.0         0.0
 4    2020-01-05          0.0        0.0           0.0         0.0
 ..          ...          ...        ...           ...         ...
 214  2020-08-02          0.0        0.0           0.0         0.0
 215  2020-08-03          0.0        0.0           0.0         0.0
 216  2020-08-04          0.0        0.0           0.0         0.0
 217  2020-08-05          0.0        0.0           0.0         0.0
 218  2020-08-06          0.0        0.0           0.0         0.0

 [219 rows x 5 columns],
 'AZE':            date  total_cases  new_cases  total_deaths  new_deaths
 0    2020-01-01          0.0        0.0           0.0         0.0
 1    2020-01-02          0.0        0.0           0.0         0.0
 2    2020-01-03          0.0        0.0           0.0         0.0
 3    2020-01-04          0.0        0.0           0.0         0.0
 4    2020-01-05          0.0        0.0           0.0         0.0
 ..          ...          ...        ...           ...         ...
 214  2020-08-02       6260.0      325.0          76.0         5.0
 215  2020-08-03       6522.0      262.0          78.0         2.0
 216  2020-08-04       6860.0      338.0          82.0         4.0
 217  2020-08-05       7239.0      379.0          84.0         2.0
 218  2020-08-06       7553.0      314.0          88.0         4.0

 [219 rows x 5 columns],
 'BIH':            date  total_cases  new_cases  total_deaths  new_deaths
 0    2020-01-01          0.0        0.0           0.0         0.0
 1    2020-01-02          0.0        0.0           0.0         0.0
 2    2020-01-03          0.0        0.0           0.0         0.0
 3    2020-01-04          0.0        0.0           0.0         0.0
 4    2020-01-05          0.0        0.0           0.0         0.0
 ..          ...          ...        ...           ...         ...
 214  2020-08-02       2550.0       16.0         156.0         0.0
 215  2020-08-03       2593.0       43.0         158.0         2.0
 216  2020-08-04       2605.0       12.0         158.0         0.0
 217  2020-08-05       2605.0        0.0         158.0         0.0
 218  2020-08-06       2605.0        0.0         158.0         0.0

 [219 rows x 5 columns],
 'BRB':            date  total_cases  new_cases  total_deaths  new_deaths
 0    2020-01-01          0.0        0.0           0.0         0.0
 1    2020-01-02          0.0        0.0           0.0         0.0
 2    2020-01-03          0.0        0.0           0.0         0.0
 3    2020-01-04          0.0        0.0           0.0         0.0
 4    2020-01-05          0.0        0.0           0.0         0.0
 ..          ...          ...        ...           ...         ...
 214  2020-08-02         92.0        0.0           7.0         0.0
 215  2020-08-03         92.0        0.0           7.0         0.0
 216  2020-08-04         92.0        0.0           7.0         0.0
 217  2020-08-05         92.0        0.0           7.0         0.0
 218  2020-08-06         92.0        0.0           7.0         0.0

 [219 rows x 5 columns],
 'BGD':            date  total_cases  new_cases  total_deaths  new_deaths
 0    2020-01-01          0.0        0.0           0.0         0.0
 1    2020-01-02          0.0        0.0           0.0         0.0
 2    2020-01-03          0.0        0.0           0.0         0.0
 3    2020-01-04          0.0        0.0           0.0         0.0
 4    2020-01-05          0.0        0.0           0.0         0.0
 ..          ...          ...        ...           ...         ...
 214  2020-08-02      55140.0     2695.0         746.0        37.0
 215  2020-08-03      57563.0     2423.0         781.0        35.0
 216  2020-08-04      60391.0     2828.0         811.0        30.0
 217  2020-08-05      63026.0     2635.0         846.0        35.0
 218  2020-08-06      65769.0     2743.0         888.0        42.0

 [219 rows x 5 columns],
 'BEL':            date  total_cases  new_cases  total_deaths  new_deaths
 0    2020-01-01          0.0        0.0           0.0         0.0
 1    2020-01-02          0.0        0.0           0.0         0.0
 2    2020-01-03          0.0        0.0           0.0         0.0
 3    2020-01-04          0.0        0.0           0.0         0.0
 4    2020-01-05          0.0        0.0           0.0         0.0
 ..          ...          ...        ...           ...         ...
 214  2020-08-02      58685.0       70.0        9522.0        17.0
 215  2020-08-03      58767.0       82.0        9548.0        26.0
 216  2020-08-04      58907.0      140.0        9566.0        18.0
 217  2020-08-05      59072.0      165.0        9580.0        14.0
 218  2020-08-06      59226.0      154.0        9595.0        15.0

 [219 rows x 5 columns],
 'BFA':            date  total_cases  new_cases  total_deaths  new_deaths
 0    2020-01-01          0.0        0.0           0.0         0.0
 1    2020-01-02          0.0        0.0           0.0         0.0
 2    2020-01-03          0.0        0.0           0.0         0.0
 3    2020-01-04          0.0        0.0           0.0         0.0
 4    2020-01-05          0.0        0.0           0.0         0.0
 ..          ...          ...        ...           ...         ...
 214  2020-08-02        884.0        1.0          53.0         0.0
 215  2020-08-03        885.0        1.0          53.0         0.0
 216  2020-08-04        888.0        3.0          53.0         0.0
 217  2020-08-05        888.0        0.0          53.0         0.0
 218  2020-08-06        889.0        1.0          53.0         0.0

 [219 rows x 5 columns],
 'BGR':            date  total_cases  new_cases  total_deaths  new_deaths
 0    2020-01-01          0.0        0.0           0.0         0.0
 1    2020-01-02          0.0        0.0           0.0         0.0
 2    2020-01-03          0.0        0.0           0.0         0.0
 3    2020-01-04          0.0        0.0           0.0         0.0
 4    2020-01-05          0.0        0.0           0.0         0.0
 ..          ...          ...        ...           ...         ...
 214  2020-08-02       2585.0       47.0         147.0         3.0
 215  2020-08-03       2585.0        0.0         147.0         0.0
 216  2020-08-04       2668.0       83.0         160.0        13.0
 217  2020-08-05       2711.0       43.0         160.0         0.0
 218  2020-08-06       2727.0       16.0         160.0         0.0

 [219 rows x 5 columns],
 'BHR':            date  total_cases  new_cases  total_deaths  new_deaths
 0    2020-01-01          0.0        0.0           0.0         0.0
 1    2020-01-02          0.0        0.0           0.0         0.0
 2    2020-01-03          0.0        0.0           0.0         0.0
 3    2020-01-04          0.0        0.0           0.0         0.0
 4    2020-01-05          0.0        0.0           0.0         0.0
 ..          ...          ...        ...           ...         ...
 214  2020-08-02      12815.0      504.0          20.0         1.0
 215  2020-08-03      13296.0      481.0          21.0         1.0
 216  2020-08-04      13835.0      539.0          23.0         2.0
 217  2020-08-05      14383.0      548.0          24.0         1.0

In [115]:
len(dic_countrys_df)
len

240

In [119]:
list_summary_deaths = []
list_summary_cases=[]
for i in range(len(dic_countrys_df)):
    list_summary_cases.append(dic_countrys_df[data_country_iso_code['ISO 3166-1 .1'][i]]['total_cases'][len(dic_countrys_df[data_country_iso_code['ISO 3166-1 .1'][0]])-1])
    list_summary_deaths.append(dic_countrys_df[data_country_iso_code['ISO 3166-1 .1'][i]]['total_deaths'][len(dic_countrys_df[data_country_iso_code['ISO 3166-1 .1'][0]])-1])

df_summary_covid= pd.DataFrame(columns=('Nombre del país','total_cases','total_deaths'))
df_summary_covid['Nombre del país'] = data_country_iso['Nombre del país']
df_summary_covid['total_cases'] = list_summary_cases
df_summary_covid['total_deaths'] = list_summary_deaths
               
df_summary_covid

                      Nombre del país  total_cases  total_deaths
ISO 3166-1 .1
AND                           Andorra        852.0          51.0
ARE            Emiratos Árabes Unidos      38808.0         276.0
AFG                        Afganistán      20342.0         357.0
ATG                 Antigua y Barbuda         26.0           3.0
AIA                           Anguila          3.0           0.0
...                               ...          ...           ...
WLF                   Wallis y Futuna          0.0           0.0
WSM                             Samoa          0.0           0.0
YEM                             Yemen        486.0         112.0
MYT                           Mayotte          0.0           0.0
ZAF                         Sudáfrica      48285.0         998.0

[240 rows x 3 columns]

In [128]:
df_summary_covid_ascendent = df_summary_covid.sort_values('total_cases',ascending=False)
df_summary_covid_ascendent

                         Nombre del país  total_cases  total_deaths
ISO 3166-1 .1
USA            Estados Unidos de América    1942363.0      110514.0
BRA                               Brasil     672846.0       35930.0
RUS                                Rusia     467673.0        5859.0
GBR                          Reino Unido     286194.0       40542.0
IND                                India     256611.0        7135.0
...                                  ...          ...           ...
MAC                                Macao          0.0           0.0
COK                           Islas Cook          0.0           0.0
TKL                              Tokelau          0.0           0.0
KLK                       Islas Malvinas          0.0           0.0
PLW                         Islas Palaos          0.0           0.0

[240 rows x 3 columns]

## 3. Integración de interfaz gráfica

In [135]:
interfaz = widgets.VBox([img_encabezado,widgets.HBox([fig_table,widgets.VBox([country_selector,fig_UpLeft,fig_DownLeft]),widgets.VBox([time_selector,fig_UpRight,fig_DownRight ])])])
interfaz

VBox(children=(Image(value=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x06\x05\x00\x00\x00\xfd\x08\x02\x00\x…

In [114]:
data_country_iso['Nombre del país']

ISO 3166-1 .1
AND                   Andorra
ARE    Emiratos Árabes Unidos
AFG                Afganistán
ATG         Antigua y Barbuda
AIA                   Anguila
                ...
WLF           Wallis y Futuna
WSM                     Samoa
YEM                     Yemen
MYT                   Mayotte
ZAF                 Sudáfrica
Name: Nombre del país, Length: 240, dtype: object

In [118]:
dic_countrys_df[data_country_iso_code['ISO 3166-1 .1'][1]]

           date  total_cases  new_cases  total_deaths  new_deaths
0    2020-01-01          0.0        0.0           0.0         0.0
1    2020-01-02          0.0        0.0           0.0         0.0
2    2020-01-03          0.0        0.0           0.0         0.0
3    2020-01-04          0.0        0.0           0.0         0.0
4    2020-01-05          0.0        0.0           0.0         0.0
..          ...          ...        ...           ...         ...
214  2020-08-02      36359.0      571.0         270.0         1.0
215  2020-08-03      37018.0      659.0         273.0         3.0
216  2020-08-04      37642.0      624.0         274.0         1.0
217  2020-08-05      38268.0      626.0         275.0         1.0
218  2020-08-06      38808.0      540.0         276.0         1.0

[219 rows x 5 columns]